remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: Anda Ziemele's ePortfolio
description: This is the GitHub page of my MSc Computer Science e-Portfolio.
